source "http://rubygems.org"

ruby "1.9.3"

gem 'bundler'
gem 'sinatra'
gem 'thin'
gem 'json_pure'
gem 'haml'
gem 'redis'
gem 'cf'
gem 'cfoundry'
gem 'logger'
gem 'uuidtools'
gem 'httpclient'
gem 'mongo'
gem 'awesome_print'
gem 'cf-autoconfig'
